version: '3'


#######################################
# docker commands:
#   - docker-compose stop
#   - docker-compose down
#   - docker-compose stop && docker-compose rm -f && docker volume prune -f && docker network prune -f
#   - docker rmi -f $(docker images -qf dangling=true)
#   - docker-compose up --remove-orphans --build --force-recreate
#   - docker ps
#
# ports: HOST(exposed to browser):CONTAINER(port services use inside docker & nginx listens to)
#######################################

services:

  #######################################
  # Jupyter
  # Jupyter available outside container @ localhost:18888
  # Tensorboard available outside container @ localhost:5001
  #######################################
  jupyter:
    container_name: "jupyter_azure"
    restart: "always"
    build: .
    environment:
      - JUPYTER_PASSWORD=pw+pw-pw=pw
    volumes:
      - '../_first_azure:/home/jovyan/aixpact/_first_azure'
      - '../_data:/home/jovyan/aixpact/_data'
      - '../_cases:/home/jovyan/aixpact/_cases'
      - '../_data_science:/home/jovyan/aixpact/_data_science'
      - '../_DL:/home/jovyan/aixpact/_DL'
      - '../_ML:/home/jovyan/aixpact/_ML'
      - '../_NLP:/home/jovyan/aixpact/_NLP'
      - '../_networks:/home/jovyan/aixpact/_networks'
      - './project:/home/jovyan/aixpact/project'
      - 'jupyter:/home/jovyan/aixpact/docker_volume'
    ports:
      - 18888:8888
      - 5001:6006
    entrypoint: sh -c 'start-notebook.sh --NotebookApp.token=$$JUPYTER_PASSWORD'


  #######################################
  # Portainer
  # Container admin
  # latest version of Portainer, 1.21.0
  #######################################
  # portainer:
  #   container_name: "portainer"
  #   restart: "always"
  #   image: 'portainer/portainer:1.21.0'
  #   command: --admin-password 'super_secret_pw'
  #   volumes:
  #     - '/var/run/docker.sock:/var/run/docker.sock'
  #     - 'portainer:/data'
  #   ports:
  #     - 9090:9000
  #   command: -H unix:///var/run/docker.sock


#######################################
# Persistent volumes
# clear all volumes: $ docker volume prune
#######################################
volumes:
  jupyter:
  # portainer:

